# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitZen < Formula
  desc "An interactive, fuzzy-searchable git branch manager"
  homepage "https://github.com/achill06/git-zen"
  version "1.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/achill06/git-zen/releases/download/v1.0.1/git-zen_Darwin_x86_64.tar.gz"
      sha256 "26b55dd3f6e2458a51c18738d6a9a1dab230d9d4cfc10693bcb80e3a836d1925"

      def install
        bin.install "git-zen"
      end
    end
    on_arm do
      url "https://github.com/achill06/git-zen/releases/download/v1.0.1/git-zen_Darwin_arm64.tar.gz"
      sha256 "e1a6701c102c01ede13400ec5dca4fe2f4422b55eab228306dfe622102d5f708"

      def install
        bin.install "git-zen"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/achill06/git-zen/releases/download/v1.0.1/git-zen_Linux_x86_64.tar.gz"
        sha256 "c911eda902de63a3511fc54c5de80ba0b1061bc576bf07b0a8d4c802328b937f"

        def install
          bin.install "git-zen"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/achill06/git-zen/releases/download/v1.0.1/git-zen_Linux_arm64.tar.gz"
        sha256 "c16d20087ac22fb70df7dec50cab9e12f0a079662047d338e97c084ac9bc7f05"

        def install
          bin.install "git-zen"
        end
      end
    end
  end
end
